### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by UnionDesign** [VineCode/Sass.novaextension#15]
Sorry not really an issue. I just need help.

How my project is setup:
- project/assets/css/style.css
- project/assets/scss/style.scss
- project/assets/scss/partials/_partial.scss

Settings in the extension (I've spend hours trying different things and nothing seems to work but right now it's set to this:

- update path: assets/sass/
- output path: assets/css/
- executable path: /Users/davidlewis/Sites/macleod/app/public/wp-content/themes/macleod/assets/sass/style.scss

Help? I can get it to work when I used the default setup suggested in the docs with the sass and css in the same directory but I'd really rather have the "source code" somewhat separate.

Oh and I'm getting errors like this right now with the first line of style.scss using an @import: like this:

@import "abstracts/_variables.scss";

/Users/davidlewis/Sites/macleod/app/public/wp-content/themes/macleod/assets/sass/style.scss: line 1: //: is a directory

**Comment by JohnWickham** [comment]
May not be much help now, but if anyone else comes across this: the executable path option is for specifying where on your system the Sass program is located. You would use this if you have a different version of the Sass compiler installed and want to use it instead. Most people won't change this setting.

In your situation, leaving the executable path field blank will use the default installed. Your update path will watch assets/sass, and output to assets/css.

**Comment by vinecode-andy** [comment]
@JohnWickham Thanks for answering :-)
