### ISSUE TITLE
Crash on save in Nova 8.0

### ISSUE THREAD

**Issue by JohnWickham** [VineCode/Sass.novaextension#27]
Using the extension in Nova 8.0 causes the app to crash when saving any file. Not immediately obvious what's causing this; I'll update and fix if I have time! (For now, avoid updating to 8.0 if using Sass is important to you).

**Comment by vinecode-andy** [comment]
Hi John, yes I am terrible at keep an eye on this repo. I had the same issue, I think a lot of extension developers did and it seems that a Nove release the day after sorted this.
