### ISSUE TITLE
Adjustable export path

### ISSUE THREAD

**Issue by MarcoPNS** [VineCode/Sass.novaextension#3]
Alot of my projects are structured like this:

```
assets/scss/ -> all my scss files
dist/css/ -> compiled css file
```

It would help me a lot if I could adjust the export path so that it match my structure.

**Comment by khaldrogo90** [comment]
There is an option now for it in the extension's settings, but it isn't working for me...

**Comment by unapieer** [comment]
> There is an option now for it in the extension's settings, but it isn't working for me...

I thought too, but I figured out that is used to set path to a folder to compiler, not an export path.

**Comment by khaldrogo90** [comment]
> I thought too, but I figured out that is used to set path to a folder to compiler, not an export path.

You're totally right, I misunterstood that too.

**Comment by patrickquirke** [comment]
I can't find the preferences to change the export paths, please help!

**Comment by vinecode-andy** [comment]
Hey all, just added a new preference where you can set the output path relative to the workspace directory. 

By setting the Update Path and Output Path, it will allow. 

```
assets/scss/ -> all my scss files
dist/css/ -> compiled css file
```
This will arrive shortly in v1.3
