### ISSUE TITLE
Indented formatting?

### ISSUE THREAD

**Issue by luxuryluke** [VineCode/Sass.novaextension#6]
I've fallen in love with the indented rule formatting output by the live sass compiler for VS Code. Also, CodeKit has a similar option.
"expanded, compact, compressed, nested"
Any chance this option can be added to your roadmap?

**Comment by vinecode-andy** [comment]
Currently in the preferences we have the CSS Style which allows you to choose Expanded or Compressed. I should be able to add Compact and Nested.

**Comment by vinecode-andy** [comment]
Sorry @luxuryluke because under the hood we are using the dart sass version only "Expanded" and "Compressed" are supported. Also see https://github.com/sass/dart-sass/issues/442
