### ISSUE TITLE
Converting SCSS to CSS does not work

### ISSUE THREAD

**Issue by uwe-kempf** [VineCode/Sass.novaextension#8]
Hi!
Can anyone help.
- HomeBrew installed
- sass installed

My SCSS
theme/scss

Target Folder ('update path' in preferences)
theme/css

It simple doesn't convert the SCSS. No error messages. 
I tried many different path options.
But it won't work.

Thanks for your help
Uwe

**Comment by vinecode-andy** [comment]
@uwe-kempf The Update path is the Source rather than the Target (Yeh a little confusing I know) I have now added a new preference that will let you set the Output folder so ...

```
Update Path: theme/scss
Output Path: theme/css
```

Hope this helps

**Comment by uwe-kempf** [comment]
Yes! Thanks a lot :-)
