### ISSUE TITLE
Unable to make output path work

### ISSUE THREAD

**Issue by elemis** [VineCode/Sass.novaextension#9]
I can't figure out how to make the output path work. This is the directory structure I have:

project/assets/custom.scss
project/dist/css

I want the /dist/css/ to be my output folder but it doesn't work if I write in the output path field like this. I tried different variations none of them worked. If I delete the path then it works again and places the .css file next to .scss, but I need to export on a different folder. Could you please point to the right direction? Thanks.

**Comment by looseknotjp** [comment]
Apparently, the reference directory for Output Path is the "vincode.Sass" folder.
So, for example, setting "../dist/css" will create a "dist / css" folder in the same directory as "vincode.Sass".
I think this needs to fix the relative directory, but how about it?

**Comment by elemis** [comment]
So I have to use a path like this to make the output inside the dist folder in the project: "../../../../../Documents/Git/development/theme-name/dist/" 

But it's dangerous when working with multiple projects. How to make this path relative to the project?

**Comment by ericksonstudio** [comment]
I agree with the above comments; it's very confusing to know how to set up the update and output directories. They should be relative to the project path since every project is different. Or at least have the ability to override the default settings with a _config.rb_ file or similar. Thanks.

**Comment by looseknotjp** [comment]
I've solved it, so I'll comment it.

Add the following to "Configuration.json" in the ".nova" folder generated in the project folder.

"VineCode.Sass.outputPath": "../../../../ ../ [YourProject] / xxx"

The reason for referencing 5 levels up is that the initial reference directory is "vincode.Sass".

**Comment by vinecode-andy** [comment]
The output path **should** be relative to the workspace path, I will look into this bug.

**Comment by jwssnr** [comment]
And it would be useful to set the paths individual per project.

**Comment by mrkbr** [comment]
Yes this is very important for almost every of my projects. Output path in project settings - please.

**Comment by byTwinn** [comment]
Same here, any news about this bug ? thanks !

**Comment by vinecode-andy** [comment]
Hey all, just pushed an update which should fix this. Let me know if it helps. Thanks

**Comment by byTwinn** [comment]
> Hey all, just pushed an update which should fix this. Let me know if it helps. Thanks

Thanks ! it's fixed here 😃
